/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tcl_alvin_tcl_drone_project_util_TCLNdkJniUtils */

#ifndef _Included_com_tcl_alvin_tcl_drone_project_util_TCLNdkJniUtils
#define _Included_com_tcl_alvin_tcl_drone_project_util_TCLNdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tcl_alvin_tcl_drone_project_util_TCLNdkJniUtils
 * Method:    naGetConvertedFrame
 * Signature: (Landroid/graphics/Bitmap;[BII)V
 */
JNIEXPORT void JNICALL Java_com_tcl_alvin_tcl_1drone_1project_util_TCLNdkJniUtils_naGetConvertedFrame
  (JNIEnv *, jclass, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
