/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tcl_alvin_tcl_drone_project_util_TCLNdkJniUtils */

#ifndef _Included_com_tcl_alvin_tcl_drone_project_util_TCLNdkJniUtils
#define _Included_com_tcl_alvin_tcl_drone_project_util_TCLNdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tcl_alvin_tcl_drone_project_util_TCLNdkJniUtils
 * Method:    getStringFormC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tcl_alvin_tcl_1drone_1project_util_TCLNdkJniUtils_getStringFormC
  (JNIEnv *, jclass);

/*
 * Class:     com_tcl_alvin_tcl_drone_project_util_TCLNdkJniUtils
 * Method:    decodeYUV420SP
 * Signature: ([BII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_tcl_alvin_tcl_1drone_1project_util_TCLNdkJniUtils_decodeYUV420SP
  (JNIEnv *, jclass, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
